image: Visual Studio 2017

platform: Any CPU

configuration: Debug

before_build:
  - nuget restore

build:
  parallel: true
  project: Project.sln

test:
  assemblies:
    only: 
      - '**\*Test.dll'
