image: Visual Studio 2017

platform: Any CPU

configuration: Debug

before_build:
  # Prefere dotnet restore over nuget restore due to "Any CPU" vs "AnyCPU" expansion of $(Platform) macro in out-of-source build configuration
  - dotnet restore

build_script:
  - dotnet build Project.sln

test:
  assemblies:
    only: 
      - '**\*UnitTest.dll'
